"""update

Revision ID: 6ee22d45320c
Revises: ef873b56e74e
Create Date: 2024-05-28 19:11:33.569380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee22d45320c'
down_revision = 'ef873b56e74e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document', sa.String(length=50), nullable=True))
        batch_op.drop_column('id_document')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_document', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('document')

    # ### end Alembic commands ###
